package com.neuedu.dao;

import com.neuedu.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    /**
     * 判断用户名是否存在
     * */
    int usernameIsexist(@Param("username") String username);
    /**
     * 判断邮箱是否存在
     * */
    int emailIsexist(@Param("email") String email);
    /**
     * 根据用户名判断密码是否正确
     * */
    String selectPasswordByUsername(@Param("username") String username);
    /**
     * 根据用户名密码查询用户信息
     * */
    User selectUserByUsernameAndPassowrd(@Param("username") String username,@Param("password") String password);
    /**
     * 根据用户名查询密保问题
     * */
    String selectQuestionByUsername(@Param("username") String username);
    /**
     * 根据用户名，问题，答案，确定答案是否正确
     * */
    int checkAnswerByUsernameAndQuestionAndAnswer(@Param("username") String username,
                                                  @Param("question") String question,
                                                  @Param("answer") String answer);
    /**
     * 忘记密码修改密码
     * */
    int updataPasswordByUsername(@Param("username") String username,
                                 @Param("password") String password);

    /**
     * 登录状态下修改部分用户信息
     * */
    int updataUserByActive(User user);

}